"""contract user id

Revision ID: ef6ac43c6dc9
Revises: e53bee78aa87
Create Date: 2026-01-20 09:33:37.008082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6ac43c6dc9'
down_revision: Union[str, Sequence[str], None] = 'e53bee78aa87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'contracts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'user_id')
    # ### end Alembic commands ###
