"""feat: r2 code

Revision ID: 52447c47304c
Revises: 5477c1faadd3
Create Date: 2026-02-09 18:27:31.533661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52447c47304c'
down_revision: Union[str, Sequence[str], None] = '5477c1faadd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('r2', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'r2')
    # ### end Alembic commands ###
