"""sponsor for contracts

Revision ID: fe1ba9a3ac00
Revises: c3d4e5f6a7b8
Create Date: 2026-02-19 16:13:07.437015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1ba9a3ac00'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'r2',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'r2',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
