"""contract model

Revision ID: e53bee78aa87
Revises: 36c5a4fff315
Create Date: 2026-01-19 20:03:23.464418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53bee78aa87'
down_revision: Union[str, Sequence[str], None] = '36c5a4fff315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('hancock_project_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_at_time', sa.Time(), nullable=True),
    sa.Column('end_at_time', sa.Time(), nullable=True),
    sa.Column('google_meet_url', sa.String(), nullable=True),
    sa.Column('inspection_doc', sa.String(), nullable=True),
    sa.Column('invoice_doc', sa.String(), nullable=True),
    sa.Column('form_stage', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
