"""zip profiles for contractors

Revision ID: 701f1586de96
Revises: b92d7dc1271d
Create Date: 2026-01-05 10:01:00.735722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701f1586de96'
down_revision: Union[str, Sequence[str], None] = 'b92d7dc1271d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('sponsored', sa.String(), nullable=False),
    sa.Column('utility_type', sa.String(), nullable=False),
    sa.Column('has_utility', sa.Boolean(), nullable=False),
    sa.Column('proceed_reason', sa.String(), nullable=False),
    sa.Column('is_dec', sa.Boolean(), nullable=False),
    sa.Column('electrification_candidate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zip_profiles')
    # ### end Alembic commands ###
