"""user name and email ghl

Revision ID: d85f99a725b4
Revises: 9c0d1e2f3a4b
Create Date: 2026-03-16 10:02:36.858408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85f99a725b4'
down_revision: Union[str, Sequence[str], None] = '9c0d1e2f3a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('client_name', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'phone_number')
    op.drop_column('contracts', 'client_name')
    # ### end Alembic commands ###
